config {
  type: "incremental",
  description: "NFL game touchdown predictions",
  uniqueKey: ["game_team_id"],
  columns: {
    game_team_id: 'Unique identifier for game and team combination',
    predicted_touchdowns: 'Predicted number of touchdowns',
    created_timestamp: 'Created timestamp'
  },
  schema: dataform.projectConfig.vars.layer_cur
}

with batched_games as (
    select
      ifnull(
        array_agg(
          json_object(
            'game_team_id', game_team_id,
            'total_first_downs', total_first_downs,
            'total_yards', total_yards,
            'interceptions', interceptions,
            'punts', punts
          )
          ignore nulls
        ), [json_object()]
      ) as batch
    from
      ${ref("game_stats")}
      ${when(incremental(), `where game_team_id not in (select distinct game_team_id from ${self()})` )}
)
, predictions as (
    select
      ${ref("nfltouchdown_cloudrun")}(parse_json(to_json_string(batch))) as predictions_json
    from
      batched_games
)
, unnested_predictions as (
    select
        json_value(prediction, '$.game_team_id') as game_team_id
      , json_value(prediction, '$.predictions[0]') as predicted_touchdowns
    from
      predictions
    , unnest(json_query_array(predictions_json, '$')) as prediction
)
select
    cast(up.game_team_id as INT64) as game_team_id
  , cast(up.predicted_touchdowns as FLOAT64) as predicted_touchdowns
  , current_timestamp() as created_timestamp
from
  unnested_predictions up